apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGpsenBvZ3Z6
  CLOUDINARY_KEY: Mzk0NzIyODU1Mzg0ODc4
  CLOUDINARY_SECRET: ODVJNE9ENGRfSDhfZU0xOGJKVThWSldGV2lB
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMmhwZG1FdGJXRndjeUlzSW1FaU9pSmpiVzF0YURnemRHUXlZbmxxTW5Cd2NtUTFObmcxTUdFM0luMC5UYmNIN1dWZ1dFZ1ZPNlc0c0Y4anJn
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjEyM0BteWNsdXN0ZXIud3luNmFobC5tb25nb2RiLm5ldC8/YXBwTmFtZT1teWNsdXN0ZXI=
